name = "MultiAffine"
uuid = "251e6cbc-5fb1-4602-bd1f-2bec286d6307"
authors = ["Olivier Verdier <olivier.verdier@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ManifoldDiff = "af67fdf4-a580-4b9f-bbec-742ef357defd"
ManifoldGroupTesting = "3d9140b9-2699-468e-abff-6b59d65ee1fd"
ManifoldGroupUtils = "1a3c8808-2843-4c72-af8e-d50ed15039bf"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
ManifoldsBase = "3362f125-f0bb-47a3-aa74-596ffd7ef2fb"

[compat]
ManifoldDiff = "0.3"
ManifoldGroupTesting = "0.1.0"
ManifoldGroupUtils = "0.1.0"
Manifolds = "0.9.18, 0.10"
ManifoldsBase = "0.15"
julia = "1.6.7"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
